### PR TITLE
feature: add configfile parameter

### PR DESCRIPTION
**Pull request by juju4**
* yaml configfile
* only few settings implemented: username, password, domain,
  domain_controller, nameserver
* mostly avoid passing password on command line where other local users
  can see and which can be captured by EDR and other tools.

### CODE REVIEW

**Comment by dirkjanm** [comment]
You can also specify the password interactively by leaving it out of the command line.
While I do see how this feature could be useful, I'm not really happy with adding another dependency (pyyaml) for such a corner case. I'll be closing this PR

**Comment by juju4** [comment]
For automation/scheduled task, interactive command line is not ideal.
Can do the same with a json or ini formatted file or just basic text file with a bit more parsing and error handling code. Any interest?

**Comment by dirkjanm** [comment]
I think a simpler solution would be to add a parameter like `--password-stdin` that changes the interactive command line to read the password from stdin instead so you could do like:
```
bloodhound-python -u test -d test --password-stdin < password.txt
```

Do note that if you want to submit a PR it needs to be signed in order to merge. You can also open an issue requesting this and then I'll add it in a future version.

**Comment by juju4** [comment]
Issue opened. thanks

**Pull request closed without merging**
